// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/applicationservice/applicationservice.proto

package go_micro_srv_applicationservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Applicationservice service

type ApplicationserviceService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	GetAllPersons(ctx context.Context, in *Message, opts ...client.CallOption) (*AllPersonResponse, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Applicationservice_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Applicationservice_PingPongService, error)
}

type applicationserviceService struct {
	c    client.Client
	name string
}

func NewApplicationserviceService(name string, c client.Client) ApplicationserviceService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.applicationservice"
	}
	return &applicationserviceService{
		c:    c,
		name: name,
	}
}

func (c *applicationserviceService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Applicationservice.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationserviceService) GetAllPersons(ctx context.Context, in *Message, opts ...client.CallOption) (*AllPersonResponse, error) {
	req := c.c.NewRequest(c.name, "Applicationservice.GetAllPersons", in)
	out := new(AllPersonResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationserviceService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Applicationservice_StreamService, error) {
	req := c.c.NewRequest(c.name, "Applicationservice.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &applicationserviceServiceStream{stream}, nil
}

type Applicationservice_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type applicationserviceServiceStream struct {
	stream client.Stream
}

func (x *applicationserviceServiceStream) Close() error {
	return x.stream.Close()
}

func (x *applicationserviceServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *applicationserviceServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *applicationserviceServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *applicationserviceService) PingPong(ctx context.Context, opts ...client.CallOption) (Applicationservice_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Applicationservice.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &applicationserviceServicePingPong{stream}, nil
}

type Applicationservice_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type applicationserviceServicePingPong struct {
	stream client.Stream
}

func (x *applicationserviceServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *applicationserviceServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *applicationserviceServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *applicationserviceServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *applicationserviceServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Applicationservice service

type ApplicationserviceHandler interface {
	Call(context.Context, *Request, *Response) error
	GetAllPersons(context.Context, *Message, *AllPersonResponse) error
	Stream(context.Context, *StreamingRequest, Applicationservice_StreamStream) error
	PingPong(context.Context, Applicationservice_PingPongStream) error
}

func RegisterApplicationserviceHandler(s server.Server, hdlr ApplicationserviceHandler, opts ...server.HandlerOption) error {
	type applicationservice interface {
		Call(ctx context.Context, in *Request, out *Response) error
		GetAllPersons(ctx context.Context, in *Message, out *AllPersonResponse) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Applicationservice struct {
		applicationservice
	}
	h := &applicationserviceHandler{hdlr}
	return s.Handle(s.NewHandler(&Applicationservice{h}, opts...))
}

type applicationserviceHandler struct {
	ApplicationserviceHandler
}

func (h *applicationserviceHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.ApplicationserviceHandler.Call(ctx, in, out)
}

func (h *applicationserviceHandler) GetAllPersons(ctx context.Context, in *Message, out *AllPersonResponse) error {
	return h.ApplicationserviceHandler.GetAllPersons(ctx, in, out)
}

func (h *applicationserviceHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ApplicationserviceHandler.Stream(ctx, m, &applicationserviceStreamStream{stream})
}

type Applicationservice_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type applicationserviceStreamStream struct {
	stream server.Stream
}

func (x *applicationserviceStreamStream) Close() error {
	return x.stream.Close()
}

func (x *applicationserviceStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *applicationserviceStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *applicationserviceStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *applicationserviceHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.ApplicationserviceHandler.PingPong(ctx, &applicationservicePingPongStream{stream})
}

type Applicationservice_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type applicationservicePingPongStream struct {
	stream server.Stream
}

func (x *applicationservicePingPongStream) Close() error {
	return x.stream.Close()
}

func (x *applicationservicePingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *applicationservicePingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *applicationservicePingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *applicationservicePingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
