// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/applicationservice/applicationservice.proto

package go_micro_srv_applicationservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_applicationservice_23bfd564b3f442c7, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Person struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  string   `protobuf:"bytes,2,opt,name=age,proto3" json:"age,omitempty"`
	Job                  string   `protobuf:"bytes,3,opt,name=job,proto3" json:"job,omitempty"`
	Id                   string   `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_applicationservice_23bfd564b3f442c7, []int{1}
}
func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (dst *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(dst, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() string {
	if m != nil {
		return m.Age
	}
	return ""
}

func (m *Person) GetJob() string {
	if m != nil {
		return m.Job
	}
	return ""
}

func (m *Person) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AllPersonResponse struct {
	Persons              []*Person `protobuf:"bytes,1,rep,name=persons,proto3" json:"persons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AllPersonResponse) Reset()         { *m = AllPersonResponse{} }
func (m *AllPersonResponse) String() string { return proto.CompactTextString(m) }
func (*AllPersonResponse) ProtoMessage()    {}
func (*AllPersonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_applicationservice_23bfd564b3f442c7, []int{2}
}
func (m *AllPersonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllPersonResponse.Unmarshal(m, b)
}
func (m *AllPersonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllPersonResponse.Marshal(b, m, deterministic)
}
func (dst *AllPersonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllPersonResponse.Merge(dst, src)
}
func (m *AllPersonResponse) XXX_Size() int {
	return xxx_messageInfo_AllPersonResponse.Size(m)
}
func (m *AllPersonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllPersonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllPersonResponse proto.InternalMessageInfo

func (m *AllPersonResponse) GetPersons() []*Person {
	if m != nil {
		return m.Persons
	}
	return nil
}

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_applicationservice_23bfd564b3f442c7, []int{3}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_applicationservice_23bfd564b3f442c7, []int{4}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type StreamingRequest struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingRequest) Reset()         { *m = StreamingRequest{} }
func (m *StreamingRequest) String() string { return proto.CompactTextString(m) }
func (*StreamingRequest) ProtoMessage()    {}
func (*StreamingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_applicationservice_23bfd564b3f442c7, []int{5}
}
func (m *StreamingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingRequest.Unmarshal(m, b)
}
func (m *StreamingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingRequest.Marshal(b, m, deterministic)
}
func (dst *StreamingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingRequest.Merge(dst, src)
}
func (m *StreamingRequest) XXX_Size() int {
	return xxx_messageInfo_StreamingRequest.Size(m)
}
func (m *StreamingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingRequest proto.InternalMessageInfo

func (m *StreamingRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type StreamingResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingResponse) Reset()         { *m = StreamingResponse{} }
func (m *StreamingResponse) String() string { return proto.CompactTextString(m) }
func (*StreamingResponse) ProtoMessage()    {}
func (*StreamingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_applicationservice_23bfd564b3f442c7, []int{6}
}
func (m *StreamingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingResponse.Unmarshal(m, b)
}
func (m *StreamingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingResponse.Marshal(b, m, deterministic)
}
func (dst *StreamingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingResponse.Merge(dst, src)
}
func (m *StreamingResponse) XXX_Size() int {
	return xxx_messageInfo_StreamingResponse.Size(m)
}
func (m *StreamingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingResponse proto.InternalMessageInfo

func (m *StreamingResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Ping struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_applicationservice_23bfd564b3f442c7, []int{7}
}
func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (dst *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(dst, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

type Pong struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_applicationservice_23bfd564b3f442c7, []int{8}
}
func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (dst *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(dst, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.applicationservice.Message")
	proto.RegisterType((*Person)(nil), "go.micro.srv.applicationservice.Person")
	proto.RegisterType((*AllPersonResponse)(nil), "go.micro.srv.applicationservice.AllPersonResponse")
	proto.RegisterType((*Request)(nil), "go.micro.srv.applicationservice.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.applicationservice.Response")
	proto.RegisterType((*StreamingRequest)(nil), "go.micro.srv.applicationservice.StreamingRequest")
	proto.RegisterType((*StreamingResponse)(nil), "go.micro.srv.applicationservice.StreamingResponse")
	proto.RegisterType((*Ping)(nil), "go.micro.srv.applicationservice.Ping")
	proto.RegisterType((*Pong)(nil), "go.micro.srv.applicationservice.Pong")
}

func init() {
	proto.RegisterFile("proto/applicationservice/applicationservice.proto", fileDescriptor_applicationservice_23bfd564b3f442c7)
}

var fileDescriptor_applicationservice_23bfd564b3f442c7 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x5d, 0x4b, 0xfb, 0x30,
	0x14, 0xc6, 0xff, 0x5d, 0xf7, 0xdf, 0xf4, 0x88, 0xb2, 0x05, 0x91, 0xe2, 0xeb, 0xc8, 0x8d, 0xf5,
	0xa6, 0xe2, 0xfc, 0x04, 0xbb, 0xf2, 0x4a, 0x18, 0x15, 0xbc, 0xcf, 0xba, 0x43, 0xc8, 0x5c, 0x7b,
	0x6a, 0x4e, 0x36, 0xf0, 0x03, 0xf8, 0xbd, 0x65, 0x69, 0x36, 0x84, 0x4d, 0x7a, 0x97, 0x3c, 0xcf,
	0xaf, 0x4f, 0xcf, 0x4b, 0xe0, 0xa9, 0xb6, 0xe4, 0xe8, 0x51, 0xd5, 0xf5, 0xd2, 0x14, 0xca, 0x19,
	0xaa, 0x18, 0xed, 0xda, 0x14, 0x78, 0x40, 0xca, 0x3c, 0x2b, 0xee, 0x34, 0x65, 0xa5, 0x29, 0x2c,
	0x65, 0x6c, 0xd7, 0xd9, 0x3e, 0x26, 0xaf, 0xa0, 0xff, 0x8a, 0xcc, 0x4a, 0xa3, 0x18, 0x40, 0xcc,
	0xea, 0x2b, 0x89, 0x46, 0x51, 0x7a, 0x9c, 0x6f, 0x8e, 0x72, 0x0a, 0xbd, 0x29, 0x5a, 0xa6, 0x4a,
	0x08, 0xe8, 0x56, 0xaa, 0xc4, 0x60, 0xfa, 0xf3, 0x86, 0x57, 0x1a, 0x93, 0x4e, 0xc3, 0x87, 0x84,
	0x05, 0xcd, 0x92, 0xb8, 0x51, 0x16, 0x34, 0x13, 0x67, 0xd0, 0x31, 0xf3, 0xa4, 0xeb, 0x85, 0x8e,
	0x99, 0xcb, 0x77, 0x18, 0x4e, 0x96, 0xcb, 0x26, 0x34, 0x47, 0xae, 0x37, 0x85, 0x88, 0x09, 0xf4,
	0x6b, 0xaf, 0x70, 0x12, 0x8d, 0xe2, 0xf4, 0x64, 0x7c, 0x9f, 0xb5, 0x94, 0x9d, 0x85, 0x84, 0xed,
	0x77, 0xf2, 0x06, 0xfa, 0x39, 0x7e, 0xae, 0x90, 0xdd, 0xa1, 0x52, 0xe5, 0x35, 0x1c, 0xed, 0xfe,
	0x36, 0x80, 0xb8, 0x64, 0xbd, 0x6d, 0xb3, 0x64, 0x2d, 0x53, 0x18, 0xbc, 0x39, 0x8b, 0xaa, 0x34,
	0x95, 0xde, 0xa6, 0x9c, 0xc3, 0xff, 0x82, 0x56, 0x95, 0xf3, 0x5c, 0x9c, 0x37, 0x17, 0xf9, 0x00,
	0xc3, 0x5f, 0x64, 0x08, 0x3c, 0x8c, 0xde, 0x42, 0x77, 0x6a, 0x2a, 0x2d, 0x2e, 0xa0, 0xc7, 0xce,
	0xd2, 0x07, 0x06, 0x3b, 0xdc, 0xbc, 0x4f, 0x7f, 0xfb, 0xe3, 0xef, 0x08, 0xc4, 0x64, 0xaf, 0x71,
	0x41, 0x70, 0xfa, 0x82, 0x6e, 0x37, 0x43, 0x16, 0x69, 0xeb, 0xac, 0xc2, 0x7e, 0x2f, 0xc7, 0xad,
	0xe4, 0xde, 0x6a, 0xe4, 0xbf, 0x59, 0xcf, 0x3f, 0xa4, 0xe7, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xfd, 0x9b, 0xb4, 0xbc, 0x7d, 0x02, 0x00, 0x00,
}
